# Generated by Django 5.1.6 on 2025-06-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_store_app', '0003_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
